### PR TITLE
Show the new wave running

### LINKED ISSUE #1926: The new occurrence appears `editing` instead of `running`
Steps to reproduce it:

1. Create a new occurrence
2. Start it
3. Go to its panel survey screen.

Expected result: on the list, the new occurrence card should appear `Running`.

Obtained result: on the list, the new occurrence card should appear `Editing`.

### PR DESCRIPTION
**Pull request by aeatencio**
Fix #1926

### CODE REVIEW

File: web/static/js/components/surveys/SurveyForm.jsx [hunk 1]
```diff
@@ -50,9 +53,18 @@ class SurveyForm extends Component {
...
-    launchSurvey(projectId, surveyId)
-      .then(() => router.push(routes.survey(projectId, surveyId)))
+    const { projectId, survey, router, dispatch } = this.props
+    launchSurvey(projectId, survey.id)
+      .then(() => {
+        if (survey.panelSurveyId) {
+          // An occurrence of the panel survey was launched -> the panel survey has changed.
+          // The Redux store must be updated with the panel survey new state.
+          dispatch(panelSurveyActions.fetchPanelSurvey(survey.projectId, survey.panelSurveyId))
+          dispatch(panelSurveysActions.fetchPanelSurveys(survey.projectId))
```
Comment (anaPerezGhiglia) [inline web/static/js/components/surveys/SurveyForm.jsx:63]: This is the third time in the code we do the exact same thing. I believe is time to extract it 🙂

**Review by anaPerezGhiglia — APPROVED** [review]
Left a suggestion, but otherwise looks good!

File: web/static/js/components/surveys/SurveyForm.jsx (hunk 1 above)
Comment (aeatencio) [reply web/static/js/components/surveys/SurveyForm.jsx:63]: I was expecting this comment 😛 I'll see what can I do 😇
