### PR TITLE
#2308: Fix SuccessRateLine chart

### LINKED ISSUE #2308: Success Rate chart has issues with the x-axis scale
After a two week of running a survey the x-axis of the success rate chart changed its scale, making it really difficutl to read.

image

This might be related to the quotas line-chart and its completion estimation

You can check an example [here](https://surveda-lk.org/projects/42/surveys/484
)

### PR DESCRIPTION
**Pull request by anaPerezGhiglia**
## Changes
* Remove the forecast for success rate values. We were trying to forecast when will the success rate percentage hit the `100%` ceil. This didn't (and doesn't) make any sense. It was this "forecasted" date the one that was messing around the x-axis, since we were selecting this date as the end-date of the chart.
* Simplify `SuccessRateLine` component by reciving a single data object instead of a list of them. This seems to be a leftover from copying Forecasts component
* Simplify `SurveyShow` component by avoid putting together quota bucket forecasts and success rate values
* Change chart title and subtitle since it was the same as the cockpit chart

### Evidence
**Before**
image

**After**

image

closes #2308

### CODE REVIEW

File: assets/js/components/charts/SuccessRateLine.jsx [hunk 1]
```diff
@@ -53,33 +53,28 @@ export default class SuccessRateLine extends Component<Props> {
...
     } else {
       initialTime = d3.timeHour.offset(
-        d3.min(flatten, (d) => d.time),
+        d3.min(data.values, (d) => d.time),
         -1
       )
-      lastTime = d3.timeMonth.offset(initialTime, 1)
-      lastTime = d3.max([d3.max(flatten, (d) => d.time), lastTime])
+      const oneMonthFromStart = d3.timeMonth.offset(initialTime, 1)
+      lastTime = d3.max([d3.max(data.values, (d) => d.time), oneMonthFromStart])
```
Comment (matiasgarciaisaia) [inline assets/js/components/charts/SuccessRateLine.jsx:71]: We could eventually add a few days of leeway for still-running surveys, to hint that it hasn't finished yet.

**Review by matiasgarciaisaia — APPROVED** [review]
👍 LGTM!

File: assets/js/components/charts/SuccessRateLine.jsx (hunk 1 above)
Comment (anaPerezGhiglia) [reply assets/js/components/charts/SuccessRateLine.jsx:71]: it's common to have surveys that last longer than one month?

Comment (matiasgarciaisaia) [reply assets/js/components/charts/SuccessRateLine.jsx:71]: I think most full-scale surveys are around one month long now, but we used to have larger ones (a bit over two months).

Comment (anaPerezGhiglia) [reply assets/js/components/charts/SuccessRateLine.jsx:71]: follow up on #2338
