### PR TITLE
Fix survey page going to top when remove respondents was clicked

### LINKED ISSUE #1537: When removing the respondents list an error is thrown
**Found in version:** 2de3bab

**Steps to reproduce:**

1. Create a Survey.
2. Upload a respondents file.
3. Remove the respondents list.

**Obtained result:**

- The following error is thrown:

"TypeError: Cannot read property 'close' of undefined
    at n.<anonymous> (https://surveda-stg.instedd.org/js/app-cb388f103bc94086c2674659ddcebe47.js?vsn=d:91:518390)
    at o (https://surveda-stg.instedd.org/js/app-cb388f103bc94086c2674659ddcebe47.js?vsn=d:119:440638)
    at Generator._invoke (https://surveda-stg.instedd.org/js/app-cb388f103bc94086c2674659ddcebe47.js?vsn=d:119:441734)
    at Generator.e.<computed> [as next] (https://surveda-stg.instedd.org/js/app-cb388f103bc94086c2674659ddcebe47.js?vsn=d:119:440817)
    at t (https://surveda-stg.instedd.org/js/app-cb388f103bc94086c2674659ddcebe47.js?vsn=d:91:515632)
    at https://surveda-stg.instedd.org/js/app-cb388f103bc94086c2674659ddcebe47.js?vsn=d:91:515726"

- The respondents list is removed.

### PR DESCRIPTION
**Pull request by danimiba**
Fixes #1537

### CODE REVIEW

File: web/static/js/components/surveys/SurveyWizardRespondentsStep.jsx [hunk 1]
```diff
@@ -192,7 +194,7 @@ class SurveyWizardRespondentsStep extends Component {
 
     const removeRespondentsLink = (groupId) => {
       if (!surveyStarted && !uploading) {
-        return <a href='#' className='modal-trigger' style={{marginRight: '0'}} onClick={() => this.openRemoveRespondentModal(this.refs.removeRespondents, groupId)}>{t('Remove respondents')}</a>
+        return <a href='#' className='modal-trigger' style={{marginRight: '0'}} onClick={(e) => this.openRemoveRespondentModal(e, this.refs.removeRespondents, groupId)}>{t('Remove respondents')}</a>
```
Comment (bcardiff) [inline web/static/js/components/surveys/SurveyWizardRespondentsStep.jsx:197]:
```suggestion
        return <a href='#' className='modal-trigger' style={{marginRight: '0'}} onClick={e => this.openRemoveRespondentModal(e, this.refs.removeRespondents, groupId)}>{t('Remove respondents')}</a>
```

FYI parens on single args are not needed. No need to change.
