### PR TITLE
 Include the folder actions in the activity log

### LINKED ISSUE #1554: Actions related to 'Folders' are not included in 'Activity' section
Found in version d7ff690

### LINKED ISSUE #1853: Removing a renamed folder errors
Steps to reproduce it:

1. Create a folder
2. Rename it
3. Delete it

The bug 👇 

error

### PR DESCRIPTION
**Pull request by aeatencio**
### The bug 🐛 

Actions related to 'Folders' are not included in 'Activity' section

### The solution 🎯 

 Include the folder actions in the activity log

Fix #1554 

folder logs

---

### Bonus track 🍬 

Fix removing a renamed folder error

Fix #1853

### CODE REVIEW

File: web/static/js/components/activity/ActivityDescription.jsx [hunk 1]
```diff
@@ -154,6 +154,18 @@ class ActivityDescription extends Component {
             return t('Section <i>{{oldSectionTitle}}</i> of <i>{{questionnaireName}}</i> renamed to <i>{{newSectionTitle}}</i>', {oldSectionTitle, questionnaireName, newSectionTitle})
         }
         break
+      case 'folder':
+        const folderName = metadata['folderName']
+        switch (activity.action) {
+          case 'create':
+            return t('Created folder <i>{{folderName}}</i>', {folderName})
+          case 'delete':
+            return t('Deleted folder <i>{{folderName}}', {folderName})
```
Comment (bcardiff) [inline web/static/js/components/activity/ActivityDescription.jsx:163]:
```suggestion
            return t('Deleted folder <i>{{folderName}}</i>', {folderName})
```

**Review by bcardiff — CHANGES_REQUESTED** [review]

**Review by bcardiff — APPROVED** [review]
