### PR TITLE
Histogram supports inactivity periods between retries

### LINKED ISSUE #1580: [Retries histogram] Retries are not included in the histogram when they are out of survey's schedule
**Version:** 05a098b

**Preconditions:**
The first **retry** will be executed during an inactivity period.

**Steps to reproduce:**

1. Launch the survey.
2. Observe the retries histogram after the first **contact** attempt.

**Obtained:**

- The respondents that will receive the first retry are not included in the histogram.

### PR DESCRIPTION
**Pull request by aeatencio**
Fix #1580

### CODE REVIEW

File: web/models/respondent.ex [hunk 1]
```diff
@@ -117,4 +118,13 @@ defmodule Ask.Respondent do
 
   def add_mode_attempt!(respondent, mode), do: respondent |> changeset(%{stats: Stats.add_attempt(respondent.stats, mode)}) |> Repo.update!
 
+  def next_final_timeout(%Respondent{} = respondent, timeout, now) do
+    timeout_at = next_raw_timeout(timeout, now)
+    (respondent |> Repo.preload(:survey)).survey
+    |> Survey.next_available_date_time(timeout_at)
+  end
+
+  def next_raw_timeout(timeout, now), do:
```
Comment (bcardiff) [inline web/models/respondent.ex]:
```suggestion
  def next_timeout_lowerbound(timeout, now), do:
```

File: web/models/respondent.ex [hunk 2]
```diff
@@ -117,4 +118,13 @@ defmodule Ask.Respondent do
 
   def add_mode_attempt!(respondent, mode), do: respondent |> changeset(%{stats: Stats.add_attempt(respondent.stats, mode)}) |> Repo.update!
 
+  def next_final_timeout(%Respondent{} = respondent, timeout, now) do
```
Comment (bcardiff) [inline web/models/respondent.ex]:
```suggestion
  # computes the date-time on which the respondent should be ... given the timeout and time-window availability
  def next_actual_timeout(%Respondent{} = respondent, timeout, now) do
```

File: test/models/respondent_test.exs [hunk 3]
```diff
@@ -59,4 +60,28 @@ defmodule Ask.RespondentTest do
 
     assert respondent.stats |> Stats.add_sent_sms |> Stats.total_sent_sms == 1
   end
+
+  test "next raw time out equals next final timeout when the survey is active" do
```
Comment (bcardiff) [inline test/models/respondent_test.exs]:
```suggestion
  test "next raw timeout equals next final timeout when the survey is active" do
```

File: test/models/respondent_test.exs [hunk 4]
```diff
@@ -59,4 +60,28 @@ defmodule Ask.RespondentTest do
...
+    respondent = insert(:respondent, survey: survey)
+    {:ok, now, _} = DateTime.from_iso8601("2000-01-01T00:00:00Z")
+    {:ok, expected_timeout, _} = DateTime.from_iso8601("2000-01-01T02:00:00Z")
+    timeout = 120
+
+    assert Respondent.next_raw_timeout(timeout, now) == expected_timeout
+    assert Respondent.next_final_timeout(respondent, timeout, now) == expected_timeout
+  end
+
+  test "next raw time out differs from next final timeout when the survey is active" do
```
Comment (bcardiff) [inline test/models/respondent_test.exs]:
```suggestion
  test "next raw timeout differs from next final timeout when the survey is active" do
```

**Comment by aeatencio** [comment]
Thanks, @bcardiff!

File: test/lib/runtime/broker_test.exs [hunk 5]
```diff
@@ -450,13 +451,13 @@ defmodule Ask.BrokerTest do
     assert respondent.stats.attempts["mobileweb"] == 1
     assert respondent.state == "active"
 
-    respondent = Repo.get!(Respondent, respondent.id)
```
Comment (matiasgarciaisaia) [inline test/lib/runtime/broker_test.exs]: This line was "refreshing" the respondent data. Are you sure skipping that is intended?

File: test/lib/runtime/broker_test.exs [hunk 6]
```diff
@@ -3953,7 +3962,7 @@ defmodule Ask.BrokerTest do
     :ok = channel_status_server |> GenServer.stop
   end
 
-  def create_running_survey_with_channel_and_respondent(steps \\ @dummy_steps, mode \\ "sms") do
+  defp create_running_survey_with_channel_and_respondent(steps \\ @dummy_steps, mode \\ "sms") do
```
Comment (matiasgarciaisaia) [inline test/lib/runtime/broker_test.exs]: Don't we want to share the function between the two test suites instead of create a copy for each of them?

File: test/models/respondent_test.exs [hunk 7]
```diff
@@ -59,4 +60,28 @@ defmodule Ask.RespondentTest do
...
+    respondent = insert(:respondent, survey: survey)
+    {:ok, now, _} = DateTime.from_iso8601("2000-01-01T00:00:00Z")
+    {:ok, expected_timeout, _} = DateTime.from_iso8601("2000-01-01T02:00:00Z")
+    timeout = 120
+
+    assert Respondent.next_timeout_lowerbound(timeout, now) == expected_timeout
+    assert Respondent.next_actual_timeout(respondent, timeout, now) == expected_timeout
+  end
+
+  test "next raw timeout differs from next final timeout when the survey is active" do
```
Comment (matiasgarciaisaia) [inline test/models/respondent_test.exs]:
```suggestion
  test "next raw timeout differs from next final timeout when the survey is inactive" do
```

File: test/lib/runtime/broker_test.exs (hunk 5 above)
Comment (aeatencio) [reply test/lib/runtime/broker_test.exs]: Yes, I'm sure. We don't need to do this again: https://github.com/instedd/surveda/pull/1585/files#diff-5de71ff0aa29249e2f49bf22956ce6a9R451

**Comment by aeatencio** [comment]
Thanks, @matiasgarciaisaia!

File: priv/repo/migrations/20191204182139_add_retry_stat_time_to_respondent.exs [hunk 8]
```diff
@@ -0,0 +1,9 @@
+defmodule Ask.Repo.Migrations.AddSectionOrderToRespondent do
```
Comment (matiasgarciaisaia) [inline priv/repo/migrations/20191204182139_add_retry_stat_time_to_respondent.exs]:
```suggestion
defmodule Ask.Repo.Migrations.AddRetryStatTimeToRespondent do
```

File: test/models/respondent_test.exs [hunk 9]
```diff
@@ -59,4 +60,28 @@ defmodule Ask.RespondentTest do
...
+
+  test "next_timeout_lowerbound differs from next_actual_timeout when the survey is inactive" do
+    survey = insert(:survey, %{schedule: Schedule.default()})
+    respondent = insert(:respondent, survey: survey)
+    {:ok, now, _} = DateTime.from_iso8601("2019-10-02T00:00:00Z")
+    {:ok, expected_timeout_lowerbound, _} = DateTime.from_iso8601("2019-10-02T02:00:00Z")
+    {:ok, expected_actual_timeout, _} = DateTime.from_iso8601("2019-10-02T09:00:00Z")
+    timeout = 120
+
+    assert Respondent.next_timeout_lowerbound(timeout, now) == expected_timeout_lowerbound
```
Comment (matiasgarciaisaia) [inline test/models/respondent_test.exs]:
```suggestion
    refuse Respondent.next_timeout_lowerbound(timeout, now) == Respondent.next_actual_timeout(respondent, timeout, now)
    assert Respondent.next_timeout_lowerbound(timeout, now) == expected_timeout_lowerbound
```

File: test/models/respondent_test.exs [hunk 10]
```diff
@@ -59,4 +60,28 @@ defmodule Ask.RespondentTest do
...
   end
+
+  test "next_timeout_lowerbound equals next_actual_timeout when the survey is active" do
+    survey = insert(:survey, %{schedule: Schedule.always()})
+    respondent = insert(:respondent, survey: survey)
+    {:ok, now, _} = DateTime.from_iso8601("2000-01-01T00:00:00Z")
+    {:ok, expected_timeout, _} = DateTime.from_iso8601("2000-01-01T02:00:00Z")
+    timeout = 120
+
+    assert Respondent.next_timeout_lowerbound(timeout, now) == expected_timeout
```
Comment (matiasgarciaisaia) [inline test/models/respondent_test.exs]:
```suggestion
    assert Respondent.next_timeout_lowerbound(timeout, now) == Respondent.next_actual_timeout(respondent, timeout, now)
    assert Respondent.next_timeout_lowerbound(timeout, now) == expected_timeout
```

File: web/models/respondent.ex [hunk 11]
```diff
@@ -117,4 +118,16 @@ defmodule Ask.Respondent do
...
+  @doc """
+  Computes the date-time on which the respondent should be retried or stalled given the timeout and time-window availability
+  """
+  def next_actual_timeout(%Respondent{} = respondent, timeout, now) do
+    timeout_at = next_timeout_lowerbound(timeout, now)
+    (respondent |> Repo.preload(:survey)).survey
+    |> Survey.next_available_date_time(timeout_at)
+  end
+
+  def next_timeout_lowerbound(timeout, now), do:
```
Comment (matiasgarciaisaia) [inline web/models/respondent.ex]:
```suggestion
  @doc """
  Computes the date-time on which the respondent would be retried or stalled, ignoring their survey's inactivity windows (ie, if it Schedule was to always run)
  """
  def next_timeout_lowerbound(timeout, now), do:
```

**Comment by matiasgarciaisaia** [comment]
👍
