### PR TITLE
Fix deprecated timezones

### LINKED ISSUE #1657: When scheduling a survey in 'US/Eastern' timezone an error is thrown
**Found in version:** https://github.com/instedd/surveda/commit/380f6e4fd29fdfa93165c88ad548ecce964c35c9

**Steps to reproduce:**

1. Go to create a Survey.
2. Select `US/Eastern` from Timezone options.
3. Schedule the survey.
4. Launch the survey.
5. Navigate to the Surveys listing and back to the Survey's overview.

**Obtained result:**
- The Surveys listing and the Survey's overview cannot be accessed.
- The following error is logged:
`RangeError: Invalid time zone specified: US/Eastern`

### PR DESCRIPTION
**Pull request by anaPerezGhiglia**
convert `survey.schedule.timezone` in `SurveyStatus.hourDescription()` to canonical 

in chrome was braking the **project-surveys** page and the **survey-overview** UI since `date.toLocaleTimeString` does not support deprecated timezones

### fix side-effect:
`SurveyStatus` component takes a little longer to render (if timezones not loaded) since is waiting for the backend response (timezones api). 

### fix bonus-track:
add a validation to avoid fetching the timezones to the backend if timezones are already loaded in the `state`

fixes #1657

### CODE REVIEW

File: web/static/js/components/surveys/SurveyStatus.jsx [hunk 1]
```diff
@@ -121,9 +131,11 @@ class SurveyStatus extends PureComponent {
           break
         } else {
           if (survey.nextScheduleTime) {
-            icon = 'access_time'
-            const date = new Date(survey.nextScheduleTime)
-            text = this.nextCallDescription(survey, date)
+            if (timezones && timezones.items) {
+              icon = 'access_time'
+              const date = new Date(survey.nextScheduleTime)
+              text = this.nextCallDescription(survey, date)
```
Comment (bcardiff) [inline web/static/js/components/surveys/SurveyStatus.jsx]: does this cause a glitch/re-layout in the ui until the timezone is loaded or the content appears without changing the position of elements once the timezones list is available?
